FROM python:3.13.7-alpine3.22@sha256:9ba6d8cbebf0fb6546ae71f2a1c14f6ffd2fdab83af7fa5669734ef30ad48844

RUN addgroup -S gateway && adduser -S gateway -G gateway
WORKDIR /app
COPY gateway.py /app/gateway.py

USER gateway
EXPOSE 5000
CMD ["python", "/app/gateway.py"]
