config:
  validation: true
  warningsAsErrors: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: false

complexity:
  active: true
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 15
  ComplexCondition:
    active: false
  ComplexInterface:
    active: false
  CyclomaticComplexMethod:
    active: false
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    allowedLines: 600
  LongMethod:
    active: true
    allowedLines: 60
  LongParameterList:
    active: false
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
  NestedBlockDepth:
    active: false
  NestedScopeFunctions:
    active: false
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: false

coroutines:
  active: true
  CoroutineLaunchedInTestWithoutRunTest:
    active: false
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: false
  RedundantSuspendModifier:
    active: false
  SleepInsteadOfDelay:
    active: false
  SuspendFunInFinallySection:
    active: false
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

style:
  active: false
